set(CHARM_DIR "/u/ajain18/reconverse_charm_integration/charm/multicore-linux-x86_64-cuda")
set(BASE_DIR "/u/ajain18/kokkos-miniapps/lulesh-2.0/kokkos-charm/")
set(CUDA_DIR "/opt/nvidia/hpc_sdk/Linux_x86_64/25.3/cuda/12.8")
set(KOKKOS_DIR "/u/ajain18/hapi_hip/shogo/charm/kokkos/install")

set(CHARMC "${CHARM_DIR}/bin/charmc")
set(CPU_OPTS "-c++-option -std=c++17 -O3 -march=native -DNDEBUG")
set(GPU_OPTS "-O3 -march=native -DNDEBUG")
set(GPU_LINK_OPTS -O3 -language charm++ -module EveryLB -L${KOKKOS_DIR}/lib64 -lkokkoscore -lkokkoscontainers -lkokkossimd -L${CUDA_DIR}/lib64 -lcuda -lcudart -Wl,-rpath,${KOKKOS_DIR}/lib64 -Wl,-rpath,${CUDA_DIR}/lib64)
set(LD_OPTS "")
set(INCS "-I${BASE_DIR}")
